This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/Users/matthias/Documents/ETH/ITET/Gruppenarbeit/Documentation/LaTeX/Simulation_of_Quantum_Dots.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Simulation_of_Quantum_Dots.acn....done (31 entries accepted, 0 rejected).
Sorting entries....done (190 comparisons).
Generating output file Simulation_of_Quantum_Dots.acr....done (35 lines written, 0 warnings).
Output written in Simulation_of_Quantum_Dots.acr.
Transcript written in Simulation_of_Quantum_Dots.alg.
